on:
  push:
    # paths:
    #   - "!*.md"
    #   - "!.github/*"
    #   - "!.github/**"
    #   - "!.gitignore"

jobs:
  test-template:
    runs-on: ubuntu-latest
    container:
      image: git.as73.inetsix.net/docker/pylab-runner:node
    steps:
      - uses: actions/checkout@v4
      - name: Install project requirements
        run: |
          apt-get update
          apt-get install -y python3-venv
          pip install --upgrade -r requirements.txt
      - name: Create project from cookiecutter
        run: |
          cookiecutter . --overwrite-if-exists --no-input
      - name: Test generated project setup
        run: |
          cd atd-lab
          make setup
          rm -rf .venv
