on:
  push:
    paths:
      - "{{cookiecutter.project | slugify}}-inventory/*.yml"
      - "{{cookiecutter.project | slugify}}-inventory/**/*.yml"
      - ".forgejo/**/avd.yml"
  #pull_request:
  #  types: [opened, synchronize, reopened]
env:
  ANTA_REPORT: "{{ cookiecutter.project | slugify}}-inventory/reports/"

jobs:
  avd-build:
    runs-on: ubuntu-latest
    container:
      image: git.as73.inetsix.net/docker/pylab-runner:node
    steps:
      - uses: actions/checkout@v4

      - name: Update requirements
        run: |
          pip install --upgrade -r requirements.txt
          ansible-galaxy collection install --force -r collections.yml

      - name: Run ANSIBLE AVD to BUILD
        run: |
          ansible-playbook playbooks/atd-fabric-deploy.yml --diff --tags build

      - name: Run AVD State validation in dry-run mode
        {% raw %}if: ${{ hashFiles('{% endraw %}{{cookiecutter.project | slugify }}-inventory/reports{% raw %}') == '' }}'{% endraw %}
        run: |
          ansible-playbook playbooks/atd-validate-states.yml --check

      - name: Upload AVD build results to repository
        run: |
          git config --global user.name 'git-actions[bot]'
          git config --global user.email 'git-actions[bot]@git.as73.inetsix.net'
          git add .
          git commit -am 'make: Auto-build results update' || true
          git push origin HEAD || true

      - name: Upload AVD artifacts to Action server
        uses: https://code.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: avd-configuration
          path: "**inventory/*"
